# Generated by Django 4.0 on 2022-01-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
