# Generated by Django 4.0 on 2022-01-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_event_city_alter_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notify',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
