# Generated by Django 4.0 on 2022-02-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_event_notify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='age',
            field=models.CharField(choices=[('below 10', 'below 10'), ('10 - 20', '10 - 20'), ('21 - 40', '21 - 40'), ('41 - 60', '41 - 60'), ('over 60', 'over 60')], max_length=10),
        ),
    ]
