# Generated by Django 4.0 on 2022-02-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_alter_volunteer_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='age',
            field=models.CharField(choices=[('below 10', 'below 10'), ('10 - 20', '10 - 20'), ('21 - 30', '21 - 30'), ('31 - 40', '31 - 40'), ('41 - 50', '41 - 50'), ('51 - 60', '51 - 60'), ('over 60', 'over 60')], max_length=10),
        ),
    ]
